# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resource_controller_extensions}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Blake Watters"]
  s.date = %q{2010-02-26}
  s.email = %q{blake@twotoasters.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/resource_controller_extensions.rb",
     "lib/resource_controller_extensions/fbml.rb",
     "lib/resource_controller_extensions/json.rb",
     "lib/resource_controller_extensions/xml.rb",
     "resource_controller_extensions.gemspec",
     "test/resource_controller_extensions_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/twotoasters/resource_controller_extensions}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Provides sensible defaults action for XML, JSON, and FBML to Resource Controller.}
  s.test_files = [
    "test/resource_controller_extensions_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

